<?php

/**
 * PluginS3ImageQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginS3ImageQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginS3ImageQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginS3ImageQueue');
    }
}